<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add punishment' => '',
  'Added' => '',
  'All of the communication punishments (such as chat gags and voice mutes) in the database can be viewed from here.' => '',
  'Already gagged' => '',
  'Already muted' => '',
  'Already punished' => '',
  'An error was occurred, code: {code}' => '',
  'Cancel' => '',
  'Comms' => '',
  'Extended, temporary and permanent punishments' => '',
  'Gag' => '',
  'Gags count' => '',
  'Hide inactive punishments' => '',
  'Import' => '',
  'Import completed' => '',
  'Import punishments' => '',
  'Imported from ExtendedComm' => '',
  'Imported from previous SourceComms version' => '',
  'Imported from same SourceComms version' => '',
  'Interface' => '',
  'Invalid punishment type' => '',
  'Last gags' => '',
  'Last mutes' => '',
  'Mute' => '',
  'Mutes count' => '',
  'Please give a short comment, why you are going to ungag &laquo;__NAME__&raquo;:' => '',
  'Please give a short comment, why you are going to unmute &laquo;__NAME__&raquo;:' => '',
  'Reason for removal' => '',
  'Removed by' => '',
  'Removed on' => '',
  'Show inactive punishments' => '',
  'Skipped' => '',
  'Table name' => '',
  'Temporary' => '',
  'Total' => '',
  'Total punishments' => '',
  'Total records' => '',
  'Ungag' => '',
  'Ungag reason' => '',
  'Unmute' => '',
  'Unmute reason' => '',
);
