<?php
/**
 * Message translations.
 *
 * @author Alex
 * @copyright (C)2013-2014 Alexandr Duplishchev.
 * @link https://github.com/d-ai/SourceComms
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add punishment' => 'Добавить блокировку',
  'Added' => 'Добавлено',
  'All of the communication punishments (such as chat gags and voice mutes) in the database can be viewed from here.' => 'Здесь вы можете посмотреть все блокировки коммуникаций (такие как отключения чата или микрофона), находящиеся в базе данных.',
  'Already gagged' => 'Чат уже отключен',
  'Already muted' => 'Микрофон уже отключен',
  'Already punished' => 'Уже заблокирован',
  'An error was occurred, code: {code}' => 'Произошла ошибка, код: {code}',
  'Cancel' => 'Отмена',
  'Comms' => 'Коммуникации',
  'Extended, temporary and permanent punishments' => 'Расширенные, временные и постоянные блокировки чата и микрофона',
  'Gag' => 'Чат',
  'Gags count' => 'Отключений чата',
  'Hide inactive punishments' => 'Скрыть неактивные блокировки',
  'Import' => 'Импортировать',
  'Import completed' => 'Импорт завершен',
  'Import punishments' => 'Импортировать блокировки',
  'Imported from ExtendedComm' => 'Импортировано из ExtendedComm',
  'Imported from previous SourceComms version' => 'Импортировано из SourceComms предыдущей версии',
  'Imported from same SourceComms version' => 'Импортировано из SourceComms аналогичной версии',
  'Invalid punishment type' => 'Неправильный тип блокировки',
  'Mute' => 'Микрофон',
  'Mutes count' => 'Отключений микрофона',
  'Please give a short comment, why you are going to ungag &laquo;__NAME__&raquo;:' => 'Пожалуйста, оставьте короткий комментарий, почему вы хотите включить чат &laquo;__NAME__&raquo;:',
  'Please give a short comment, why you are going to unmute &laquo;__NAME__&raquo;:' => 'Пожалуйста, оставьте короткий комментарий, почему вы хотите включить микрофон &laquo;__NAME__&raquo;:',
  'Reason for removal' => 'Причина снятия',
  'Removed by' => 'Блокировку снял',
  'Removed on' => 'Снято',
  'Show inactive punishments' => 'Показать неактивные блокировки',
  'Skipped' => 'Пропущено',
  'Table name' => 'Имя таблицы',
  'Temporary' => 'Временно',
  'Total punishments' => 'Всего блокировок',
  'Total records' => 'Всего записей',
  'Ungag' => 'Включить чат',
  'Ungag reason' => 'Причина включения чата',
  'Unmute' => 'Включить микрофон',
  'Unmute reason' => 'Причина включения микрофона',
);
