<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add punishment' => 'Добавить блокировку',
  'All of the communication punishments (such as chat gags and voice mutes) in the database can be viewed from here.' => 'Все блокировки коммуникаций (такие как отключения чата или микрофона) в базе данных - могут быть просмотрены здесь',
  'Comms' => 'Чат и микрофон',
  'Extended, temporary and permanent punishments' => 'Расширенные, временные и постоянные блокировки чата и микрофона',
  'Gag' => 'Чат',
  'Import punishments' => 'Импортировать блокировки',
  'Mute' => 'Микрофон',
  'Temporary' => 'Временно',
);
