<?php
/**
 * Message translations.
 *
 * @author Alex
 * @copyright (C)2013-2014 Alexandr Duplishchev.
 * @link https://github.com/d-ai/SourceComms
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Ban communication' => 'Добавление блокировок общения',
  'Delete communication punishments' => 'Удаление блокировок общения',
  'Edit all communication punishments' => 'Редактирование всех блокировок общения',
  'Edit group communication punishments' => 'Редактирование блокировок общения группы',
  'Edit own communication punishments' => 'Редактирование собственных блокировок общения',
  'Import communication punishments' => 'Импорт блокировок общения',
  'Unban all communication punishments' => 'Снятие всех блокировок общения',
  'Unban group communication punishments' => 'Снятие блокировок общения группы',
  'Unban own communication punishments' => 'Снятие собственных блокировок общения',
);
